### ISSUE TITLE
Base app name

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/dam2-final-project#2]
## Description

As the application is intended to be used as a platform, we shouldn't name it as a specific type of data management app, but more like a generic data management platform. Suggested names are:

- DataFlow: It's easy to remember and pronounce, and suggests an efficient and fluid flow of data.

- BizData: It's short, easy to remember and pronounce, and suggests a business application for data management.

- DataWorks: It's easy to remember and pronounce, and suggests an application that helps make data "work" effectively.

- InfoPro: It's short, easy to remember and pronounce, and suggests a professional application for information management.

- WorkFlowPro: It's easy to remember and pronounce, and suggests an application that helps improve efficiency in business workflows.

Currently, and as a placeholder, I'll use DataWorks, but feel free to suggest new ones.

## TODO

- [x] Select a marketable name for the app

**Comment by deveshaha** [comment]
I agree on the name bring "DataWorks", it is a generic name but clients can choose the name for their app.

**Comment by alexaib2002** [comment]
Closing issue, as the app name has been decided
